apiVersion: v1
kind: Service
metadata:
  name: polaris-updateservice
spec:
  selector:
    app: polaris-updateservice
  ports:
    - protocol: TCP
      port: 8084       # Porta exposta pelo serviço
      targetPort: 8084 # Porta do contêiner
      nodePort: 30084 # Porta externa
  type: LoadBalancer
